-- Downsized front cover (~400px) used by the library grids/bins/search so they
-- don't load full-resolution sleeves. Generated by the worker (sharp).
ALTER TABLE "releases" ADD COLUMN "coverThumbPath" TEXT;
